# Generated by Django 2.2.5 on 2019-09-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='corpo',
            field=models.CharField(max_length=9000),
        ),
    ]
