# Generated by Django 2.2.5 on 2019-09-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0002_auto_20190925_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='corpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='descricao',
            field=models.CharField(max_length=9000),
        ),
    ]
