# Generated by Django 2.2.5 on 2019-09-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0003_auto_20190925_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descricao',
            field=models.TextField(),
        ),
    ]
