# Generated by Django 2.2.5 on 2019-09-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0004_auto_20190925_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
