# Generated by Django 2.2.5 on 2019-09-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0006_auto_20190926_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nome',
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagem1',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagem2',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensagem',
            field=models.TextField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='noticias',
        ),
        migrations.AddField(
            model_name='comentario',
            name='noticias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmm', to='cchNoticias.Noticias'),
        ),
    ]
