# Generated by Django 2.2.5 on 2019-09-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0007_auto_20190926_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='imagem1',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='imagem2',
        ),
    ]
