# Generated by Django 2.2.5 on 2019-09-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0008_auto_20190926_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagem2',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
