# Generated by Django 2.2.5 on 2019-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0009_noticias_imagem2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='imagem',
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagem1',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem2',
            field=models.TextField(default='', max_length=50),
        ),
    ]
