# Generated by Django 2.2.5 on 2019-09-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0010_auto_20190927_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='imagem1',
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagem',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagem2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
