# Generated by Django 2.2.5 on 2019-09-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cchNoticias', '0011_auto_20190927_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='noticias',
            new_name='blog',
        ),
    ]
